name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '31 7 * * *'
  workflow_dispatch:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Checkout Plex Docker image repo
        uses: actions/checkout@v3
        with:
          repository: plexinc/pms-docker
          path: pms-docker

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@f3c664df7af409cb4873aa5068053ba9d61a57b6 #v2.6.0
        with:
          cosign-release: 'v1.13.1'

      # Added to fix https://github.com/docker/buildx/issues/499#issuecomment-763920971
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
      
      - name: Modify Dockerfile (amd64)
        # Based on https://stackoverflow.com/a/26958397/2378368
        run: sed -ie '1 s;$; AS base-amd64;' pms-docker/Dockerfile
      
      - name: Modify Dockerfile (i386)
      # Based on https://stackoverflow.com/a/26958397/2378368
        run: sed -ie '1 s;$; AS base-386;' pms-docker/Dockerfile.i386
      
      - name: Modify Dockerfile (arm/v7)
        # Based on https://stackoverflow.com/a/26958397/2378368
        run: sed -ie '1 s;$; AS base-arm/v7;' pms-docker/Dockerfile.armv7
      
      - name: Modify Dockerfile (arm64/v8)
        # Based on https://stackoverflow.com/a/26958397/2378368
        run: sed -ie '1 s;$; AS base-arm64/v8;' pms-docker/Dockerfile.arm64
      
      - name: Initialize merged Dockerfile
        run: cp pms-docker/Dockerfile Dockerfile.merged
      
      - name: Append i386 Dockerfile
        run: cat pms-docker/Dockerfile.i386 >> Dockerfile.merged
        
      - name: Append arm64 Dockerfile
        run: cat pms-docker/Dockerfile.arm64 >> Dockerfile.merged

      - name: Append armv7 Dockerfile
        run: cat pms-docker/Dockerfile.armv7 >> Dockerfile.merged

      - name: Append final Dockerfile
        run: cat Dockerfile >> Dockerfile.merged

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64, linux/arm64/v8, linux/386, linux/arm/v7
          file: ./Dockerfile.merged


      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.build-and-push.outputs.digest }}
